[package]
name = "derivation_tree"
version = "0.1.0"
edition = "2021"
description = "Utilities for describing derivation trees."
repository = "https://github.com/DavePearce/DerivationTree"

[dependencies]
